config/routes.rb
Doubleoweb::Application.routes.draw do
  post 'login' => 'users#login', :as=>'login'
  resources :users

  get "search/index"
  get "search/new"
  get "validations/index"
  get "validations/new"
  root :to=>'posts#index'
  resources :posts

  

end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/city.rb
class City < ActiveRecord::Base

  belongs_to :state

end

app/models/country.rb
class Country < ActiveRecord::Base
  has_many :states

end

app/models/email.rb
class Email < ActiveRecord::Base

  has_many :posts, :as => :postable

  def self.set_email(params)
    rand_name = "user-#{Random.new.rand(0..9999)}-#{Random.new.rand(0..99999999)}-#{Random.new.rand(0..99999999)}"
    email = self.create(:name => params[:email], :rand_name => rand_name, :use_rand => params[:actual])
    email
  end

end

app/models/job.rb
class Job < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base

  belongs_to :postable, :polymorphic => true

  searchable do
    text :text_title
  end 

  def generate_post(title, email, params)
    email = Email.set_email(params)
    params[:post].merge!(:text_title => title)
    params[:post].merge!(:validation_key => key)
    params[:post].reject!{|k, v| k == "country_id"}
    params[:post].reject!{|k, v| k == "state_id"}
    send_email(email.name, key)
    params[:post].permit!
    email.posts.create(params[:post])
  end

  def send_email(email, validation_key)
    Thread.new do
      ValidationMailer.welcome_email(email, validation_key).deliver
    end
  end

  def key
    "#{Random.new.rand(0..9999)}-#{Random.new.rand(500..999999)}-#{Random.new.rand(0..9999999)}"
  end

end

app/models/state.rb
class State < ActiveRecord::Base
  belongs_to :country
  has_many :cities

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :posts, :as => :postable

  def self.current=(user)
    Thread.current[:user] = user
  end

  def self.current
    Thread.current[:user] 
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  protected
  def authenticate
    authenticate_or_request_with_http_basic do |username, password|
      username == "admin" && password == "password"
    end
  end



end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_filter :set_cookies, :only=>:index
  before_filter :authenticate, :only=>:index
  
  def set_cookies
    if params[:country_id]
      cookies[:country_id] = params[:country_id]
    end
    if params[:state_id]
      cookies[:state_id] = params[:state_id]
    end
    if params[:city_id]
      cookies[:city_id] = params[:city_id]
    end
  end

  def index
    if params[:country_id]
      states = Country.find(params[:country_id]).states
    end
    if params[:state_id]
      cities = State.find(params[:state_id]).cities
    end
    @posts = Post.where(:city_id => cookies[:city_id], :category_id => params[:category_id], :active => true)
    respond_to do |format|
      format.js {render :js=>"populateOptions(#{states.to_json}, #{cities.to_json})"}
      format.html
    end
  end

  def show
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params).generate_post(params[:post][:title], params[:email], params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    @post = Post.where(:id => params[:id]).first
    respond_to do |format|
      if @post.update_attributes(post_params.except(:publish))
        if post_params[:publish]
          format.html { redirect_to validations_index_path(:validation_key => @post.validation_key), notice: 'Post was successfully updated.' }
        else
          format.html { redirect_to @post, notice: 'Post was successfully updated.' }
          format.json { head :no_content }
        end
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :owner_id, :city_id, :category_id, :email, :publish)
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
  end

  def new
    @search = Post.search do
      keywords params[:search]
    end
    
    @posts = @search.results
    render 'posts/index'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def login
    user = User.find_by_email_and_passcode(params[:email], params[:passcode])
    if user.present?
      User.current = user
      flash[:success] = 'Successfully logged in'
      redirect_to '/'
    else
      flash[:error] = 'User does not exist'
      redirect_to users_path
    end

  end
  
  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end
  
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        User.current = @user
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :passcode, :active)
    end
end

app/controllers/validations_controller.rb
class ValidationsController < ApplicationController
  def index
    @post = Post.where(:validation_key=>params[:validation_key]).first
  end

  def new
    Post.find(params[:id]).update_attribute(:active, true)
    flash[:success] = 'Post successfully activated'
    redirect_to post_path(Post.find(params[:id]))
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper

  def active_category
    if params[:category_id]
      "Current Listings - #{Category.find(params[:category_id]).name}"
    else
      "Welcome to doubleoweb, your online classifieds source!"
    end
  end

end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/validations_helper.rb
module ValidationsHelper
end

app/views/layouts/Posts.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Doubleoweb"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'


  %body
    .navbar.navbar-fluid-top
      .navbar-inner
        .container-fluid
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand(href="#") Doubleoweb
          .container.nav-collapse
            %ul.nav
              %li= link_to "Link 1", "/path1"
              %li= link_to "Link 2", "/path2"
              %li= link_to "Link 3", "/path3"

    .container-fluid

      .row-fluid
        .span3
          .well.sidebar-nav
            %ul.nav.nav-list
              %li.nav-header Sidebar
              %li= link_to "Link 1", "/path1"
              %li= link_to "Link 2", "/path2"
              %li= link_to "Link 3", "/path3"
        .span9
          = bootstrap_flash
          = yield
    
      %footer
        %p &copy; Company 2013
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Doubleoweb"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'


  %body
    .navbar.navbar-fluid-top
      .navbar-inner
        .container-fluid
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand(href="#") doubleoweb classifieds
          .container.nav-collapse
            %ul.nav
              %li= link_to "Post", new_post_path
              %li= link_to "My Account", users_path

    .container-fluid

      .row-fluid
        .span3
          .well.sidebar-nav
            %ul.nav.nav-list
              %li 
                Search: 
                =form_tag search_new_path, :method=>'get' do
                  =text_field_tag 'search'
                  =submit_tag 'search'
              %li.nav-header
                .left{:onclick=>"slide('for_sale')"} 
                  For Sale
                .right
                  =link_to_function image_tag('icon_expand.gif'), "slide('for_sale')"
                %div{:style=>"clear:both"}
              %li
                %ul.nav.nav-list.for_sale{:style=>'display:none'}
                  -Category.where(:post_type=>'for_sale').each do |cat|
                    %li 
                      =link_to cat.name, posts_path(:category_id=>cat.id)
              %li.nav-header
                %div{:style=>"clear:both"}
                .left{:onclick=>"slide('jobs')"} 
                  Jobs
                .right
                  =link_to_function image_tag('icon_expand.gif'), "slide('jobs')"
                %div{:style=>"clear:both"}
              %li
                %ul.nav.nav-list.jobs{:style=>'display:none'}
                  -Category.where(:post_type=>'jobs').each do |cat|
                    %li 
                      =link_to cat.name, posts_path(:category_id=>cat.id)

        .span8
          = bootstrap_flash
          %ul
            %li.left
              =label_tag Country
              =select_tag :country, options_from_collection_for_select(Country.all, 'id', 'name', cookies[:country_id]), :include_blank=>true, :onchange=>"selectCountry(this.value)"
            %li.left
              =label_tag State
              =select_tag :state, options_from_collection_for_select((cookies[:country_id].present? ? Country.find(cookies[:country_id]).states : []), 'id', 'name', cookies[:state_id]), :onchange=>"selectState(this.value)"
            %li.left
              =label_tag City
              =select_tag :city, options_from_collection_for_select((cookies[:state_id].present? ? State.find(cookies[:state_id]).cities : []), 'id', 'name', cookies[:city_id]), :onchange=>"selectCity(this.value)"
          %div{:style=>'clear:both'}
          %hr
          = yield
    
      %footer
        %p &copy; Company 2013
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"

app/views/layouts/fluid.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Doubleoweb"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'


  %body
    .navbar.navbar-application-top
      .navbar-inner
        .container
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand(href="#") Doubleoweb
          .container.nav-collapse
            %ul.nav
              %li= link_to "Link 1", "/path1"
              %li= link_to "Link 2", "/path2"
              %li= link_to "Link 3", "/path3"

    .container

      .row
        .span9
          = bootstrap_flash
          = yield
        .span3
          .well.sidebar-nav
            %h3 Sidebar
            %ul.nav.nav-list
              %li.nav-header Sidebar
              %li= link_to "Link 1", "/path1"
              %li= link_to "Link 2", "/path2"
              %li= link_to "Link 3", "/path3"
    
      %footer
        %p &copy; Company 2013
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"

app/views/posts/_form.html.haml
= form_for @post, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :title, :class => 'control-label'
    .controls
      = f.text_field :title, :class => 'text_field left'
      = f.select :category_id, options_from_collection_for_select(Category.all, 'id', 'name'), :class=>'right'
      %br
      -if !User.current
        =label_tag :email, 'Email:'
        =text_field_tag :email, '', :class=>'left'
      -else
        =hidden_field_tag :email, User.current.email
      %hr
      Show email as:
      %br
      %ul
        %li.left.marginedLeft
          =radio_button_tag :actual, true, false, :class=>'left'
        %li.left.marginedLeft
          =label_tag :actual_true, 'Actual', :class=>'left'
        %li.left.marginedLeft
          =radio_button_tag :actual, false, true, :class=>'left'
        %li.left.marginedLeft
          =label_tag :actual_false, 'Anonymous', :class=>'left'
  .control-group
    .controls
      = f.text_area :content, :class => 'text_field', :rows=>20, :style=>'width:700px'
  .form-actions
    = f.hidden_field :country_id, :value=>cookies[:country_id]
    = f.hidden_field :state_id, :value=>cookies[:state_id]
    = f.hidden_field :city_id, :value=>cookies[:city_id]
    -if params[:publish]
      = f.hidden_field :publish, :value=>true
      = f.submit nil, :class => 'btn btn-primary'
    -else
      = f.submit nil, :class => 'btn btn-primary'
      = link_to t('.cancel', :default => t("helpers.links.cancel")), posts_path, :class => 'btn'

app/views/posts/_posts.html.haml
=@posts.each do |post|
  =post

app/views/posts/edit.html.haml
- model_class = Post
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/posts/index.html.haml
%h3 
  =active_category
%hr
%br

%table
  - if @posts.present?
    - @posts.each do |post|
      %tr
        %td{:style=>'width:300px'}= post.title
        %td= link_to 'Show', post
  -else
    %h4
      -if params[:category_id]
        There are no listings for this category right now.
      -else
        Please select your location above and then select the category on the right to get started.
%br

app/views/posts/new.html.haml
- model_class = Post
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/posts/show.html.haml
- model_class = Post
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:title) + ':'
  %br
  = @post.title
%p
  %strong= model_class.human_attribute_name(:content) + ':'
  %br
  = raw simple_format @post.content

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), posts_path, :class => 'btn'

app/views/search/index.html.haml
%h1 Search#index
%p Find me in app/views/search/index.html.haml

app/views/search/new.html.haml
%h1 Search#new
%p Find me in app/views/search/new.html.haml

app/views/users/_form.html.haml
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :passcode
    = f.text_field :passcode
  .field
    = f.label :active
    = f.check_box :active
  .actions
    = f.submit 'Save'

app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

app/views/users/index.html.haml
%h4
  Login
  %hr
  =form_tag login_path do
    =label_tag :email
    =text_field_tag :email
    =label_tag :passcode
    =text_field_tag :passcode
    %br
    =submit_tag :login

%h4
  Create an account to access your listings more easily.
  %hr
  -user = User.new
  =form_for user do |f|
    =f.label :email
    =f.text_field :email
    =f.label :passcode
    =f.text_field :passcode
    %br
    =f.submit

app/views/users/new.html.haml
%h1 New user

= render 'form'

= link_to 'Back', users_path

app/views/users/show.html.haml
%p#notice= notice

%p
  %b Email:
  = @user.email
%p
  %b Passcode:
  = @user.passcode
%p
  %b Active:
  = @user.active

= link_to 'Edit', edit_user_path(@user)
\|
= link_to 'Back', users_path

app/views/validations/index.html.haml
-if @post
  %h1 
    =@post.title
  %p
    =@post.content
  %hr
  %br
  .form-actions
    =link_to 'Publish', validations_new_path(:id=>@post.id), :class=>'btn'
    = link_to t('.edit', :default => t("helpers.links.edit")), edit_post_path(@post, :publish=>true), :class => 'btn'
    = link_to t('.destroy', :default => t("helpers.links.destroy")), post_path(@post), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'
-else
  %h1
    Post was not found!